

import UIKit
enum Side {
    case left
    case right
}

class PhotoInputedIngredient : Equatable {
    static func == (lhs: PhotoInputedIngredient, rhs: PhotoInputedIngredient) -> Bool {
        lhs.title == rhs.title
    }
    
    var image : UIImage!
    
    var title : String?
    
    var buttonSide : Side?
    
    var leftPropablyTitle : String?
    
    var rightPropablyTitle : String?
    
    var outputedIngredient : Ingredient?
    
    init(image : UIImage) {
        self.image = image
    }
    
    init(image : UIImage, leftTitle : String?, rightTitle : String?) {
        self.image = image
        self.leftPropablyTitle = leftTitle
        self.rightPropablyTitle = rightTitle
    }
    
    func getTranslatedName(key : String?) -> String? {
        guard let key = key else {
            return nil
        }
        if let name = PhotoInputedIngredient.recognizeTranslateDict[key] {
            return name
        }
        return key
        
    }
    
    static let recognizeTranslateDict : Dictionary<String, String> = [
        "acorn squash": "橡實南瓜",
        "ahipa": "豆薯",
        "alcohol": "酒精",
        "ale": "麥芽啤酒",
        "alfalfa sprouts": "苜蓿芽",
        "aliment": "食物",
        "allspice": "多香果",
        "almond": "杏仁",
        "amaranth": "莧菜",
        "anchovy": "鯷魚",
        "angel-hair pasta": "天使麵",
        "anise": "八角",
        "antipasto": "開胃菜",
        "aonori": "青海苔",
        "aperitif": "開胃酒",
        "apple": "蘋果",
        "apple pie": "蘋果派",
        "apple sauce": "蘋果醬",
        "apricot pits": "杏仁核",
        "arracacha": "秘魯胡蘿蔔",
        "artichoke": "朝鮮薊",
        "arugula": "芝麻菜",
        "asparagus": "蘆筍",
        "aspic": "肉凍",
        "aubergine": "茄子",
        "avocado": "酪梨",
        "azuki bean": "紅豆",
        "baby back ribs": "小排骨",
        "bacon": "培根",
        "bagel": "貝果",
        "baguette": "法棍麵包",
        "baked alaska": "烤冰淇淋",
        "baked beans": "烤豆",
        "baklava": "果仁蜜餅",
        "balsamic": "巴薩米克醋",
        "bamboo shoots": "竹筍",
        "banana": "香蕉",
        "barbecue": "烤肉",
        "barbecue sauce": "烤肉醬",
        "barley": "大麥",
        "basil": "羅勒",
        "bass": "鱸魚",
        "batter": "麵糊",
        "bay leaf": "月桂葉",
        "beancurd": "豆腐",
        "beans": "豆子",
        "bechamel": "白醬",
        "beef": "牛肉",
        "beef carpaccio": "生牛肉片",
        "beef steak": "牛排",
        "beef tartare": "韃靼牛肉",
        "beer": "啤酒",
        "beet": "甜菜根",
        "beet root": "甜菜根",
        "beet salad": "甜菜根沙拉",
        "beignets": "法式炸甜餅",
        "berry": "莓果",
        "beverage": "飲料",
        "bibimbap": "韓式拌飯",
        "bilberry": "歐洲藍莓",
        "bird": "鳥肉",
        "birthday cake": "生日蛋糕",
        "biscuits": "餅乾",
        "bitter gourd": "苦瓜",
        "bitter melon": "苦瓜",
        "black beans": "黑豆",
        "black coffee": "黑咖啡",
        "black currant": "黑加侖",
        "black tea": "紅茶",
        "blackberry": "黑莓",
        "blancmange": "白果凍",
        "blood orange": "血橙",
        "blood sausage": "血腸",
        "blue cheese": "藍紋乳酪",
        "blueberry": "藍莓",
        "blueberry muffin": "藍莓鬆餅",
        "blueberry pie": "藍莓派",
        "bok choy": "青江菜",
        "bonbon": "糖果",
        "bonbons": "糖果",
        "booze": "酒",
        "borage": "琉璃苣",
        "boysenberry": "波森莓",
        "bran": "麥麩",
        "brandy": "白蘭地",
        "bratwurst": "德式香腸",
        "bread": "麵包",
        "bread pudding": "麵包布丁",
        "bread rolls": "麵包捲",
        "breadcrumb": "麵包屑",
        "breadfruit": "麵包果",
        "breadstick": "麵包條",
        "bream": "鯛魚",
        "brie": "布里乳酪",
        "brinjal": "茄子",
        "brioche": "奶油麵包",
        "brisket": "牛胸肉",
        "brittle": "脆糖",
        "broad beans": "蠶豆",
        "broccoli": "花椰菜",
        "broccolini": "芽芯菜",
        "broil": "烤",
        "broth": "湯",
        "brown bread": "全麥麵包",
        "brown rice": "糙米",
        "brownie": "布朗尼",
        "brulee": "焦糖",
        "bruschetta": "義式烤麵包",
        "brussels sprout": "抱子甘藍",
        "buckwheat": "蕎麥",
        "bun": "小圓麵包",
        "burdock": "牛蒡",
        "burrito": "墨西哥捲餅",
        "butter": "奶油",
        "buttercream": "奶油霜",
        "cabbage": "高麗菜",
        "caesar salad": "凱撒沙拉",
        "cake": "蛋糕",
        "cake mix": "蛋糕粉",
        "cake pop": "蛋糕棒棒糖",
        "calamari": "炸魷魚圈",
        "camembert": "卡門貝爾乳酪",
        "canape": "小點心",
        "candy": "糖果",
        "candy apple": "糖葫蘆",
        "candy bar": "巧克力棒",
        "cannoli": "義式捲管甜點",
        "cantaloupe": "哈密瓜",
        "cappuccino": "卡布奇諾",
        "caprese salad": "卡布里沙拉",
        "caramel": "焦糖",
        "caramel apple": "焦糖蘋果",
        "caraway": "葛縷子",
        "carbohydrate": "碳水化合物",
        "cardamom": "小豆蔻",
        "cardoon": "刺芹",
        "carp": "鯉魚",
        "carpaccio": "生肉片",
        "carrot": "胡蘿蔔",
        "carrot cake": "胡蘿蔔蛋糕",
        "cashew": "腰果",
        "cassava": "木薯",
        "casserole": "焗烤",
        "cauliflower": "花椰菜",
        "caviar": "魚子醬",
        "cayenne": "辣椒粉",
        "cayenne pepper": "卡宴辣椒",
        "celeriac": "根芹",
        "celery": "芹菜",
        "celtuce": "萵苣",
        "cereal": "穀片",
        "cereal bar": "穀物棒",
        "ceviche": "酸檸汁醃魚",
        "champagne": "香檳",
        "chard": "瑞士甜菜",
        "chaya": "樹菠菜",
        "chayote": "佛手瓜",
        "cheddar": "切達乳酪",
        "cheese": "起司",
        "cheesecake": "起司蛋糕",
        "cherimoya": "番荔枝",
        "cherry": "櫻桃",
        "cherry tomato": "小番茄",
        "chestnut": "栗子",
        "chevre": "山羊乳酪",
        "chicken": "雞肉",
        "chicken breast": "雞胸肉",
        "chicken curry": "咖哩雞",
        "chicken leg": "雞腿",
        "chicken quesadilla": "墨西哥雞肉夾餅",
        "chicken wings": "雞翅",
        "chickpeas": "鷹嘴豆",
        "chickweed": "繁縷",
        "chicory": "菊苣",
        "chili": "辣椒",
        "chili pepper": "辣椒",
        "chili powder": "辣椒粉",
        "chili sauce": "辣椒醬",
        "chinese artichoke": "草石蠶",
        "chips": "洋芋片",
        "chives": "韭菜",
        "chocolate": "巧克力",
        "chocolate bar": "巧克力棒",
        "chocolate cake": "巧克力蛋糕",
        "chocolate candy": "巧克力糖",
        "chocolate chip cake": "巧克力豆蛋糕",
        "chocolate cookie": "巧克力餅乾",
        "chocolate cupcake": "巧克力杯子蛋糕",
        "chocolate ice cream": "巧克力冰淇淋",
        "chocolate mousse": "巧克力慕斯",
        "chorizo": "西班牙臘腸",
        "chowder": "濃湯",
        "churros": "吉拿棒",
        "chutney": "印度調味醬",
        "ciabatta": "夏巴塔麵包",
        "cider": "蘋果酒",
        "cilantro": "香菜",
        "cinnamon": "肉桂",
        "cinnamon roll": "肉桂捲",
        "citron": "香櫞",
        "citrus": "柑橘類",
        "clam": "蛤蜊",
        "clam chowder": "蛤蜊濃湯",
        "clementine": "甜橘",
        "cloudberry": "雲莓",
        "cloves": "丁香",
        "cobbler": "水果餡餅",
        "cockle": "海瓜子",
        "cocktail": "雞尾酒",
        "cocoa": "可可",
        "coconut": "椰子",
        "coffee": "咖啡",
        "cognac": "干邑白蘭地",
        "coke": "可樂",
        "cole slaw": "涼拌高麗菜",
        "coleslaw": "涼拌高麗菜",
        "collards": "羽衣甘藍",
        "collation": "點心",
        "comestible": "食品",
        "common bean": "菜豆",
        "common purslane": "馬齒莧",
        "compote": "水果糖漿",
        "condiment": "調味料",
        "cooked meat": "熟肉",
        "cookie": "餅乾",
        "coriander": "香菜",
        "corn": "玉米",
        "corn bread": "玉米麵包",
        "corn salad": "玉米沙拉",
        "corned beef": "醃牛肉",
        "cornflakes": "玉米片",
        "cottage cheese": "茅屋起司",
        "coulis": "水果醬",
        "courgette": "櫛瓜",
        "couscous": "北非小米",
        "crab": "螃蟹",
        "crab cakes": "蟹肉餅",
        "cracker": "餅乾",
        "cranberries": "蔓越莓",
        "cranberry": "蔓越莓",
        "cranberry sauce": "蔓越莓醬",
        "crayfish": "小龍蝦",
        "cream": "鮮奶油",
        "cream cheese": "奶油起司",
        "creme brulee": "焦糖布丁",
        "crepe": "可麗餅",
        "crescent roll": "牛角麵包",
        "cress": "水芹",
        "crispbread": "脆餅",
        "croissant": "可頌",
        "croque madame": "法式火腿蛋三明治",
        "croquette": "可樂餅",
        "crouton": "麵包丁",
        "crumble": "果醬酥",
        "crunch": "脆片",
        "crust": "外皮",
        "cucumber": "小黃瓜",
        "cumin": "孜然",
        "cupcake": "杯子蛋糕",
        "curd": "凝乳",
        "currant": "醋栗",
        "curry": "咖哩",
        "custard": "蛋奶醬",
        "cutlet": "肉排",
        "cuttlefish": "花枝",
        "daikon": "白蘿蔔",
        "dairy": "乳製品",
        "dairy product": "乳製品",
        "damson": "西梅",
        "dandelion greens": "蒲公英葉",
        "danish pastry": "丹麥麵包",
        "date": "椰棗",
        "decaffeinated coffee": "無咖啡因咖啡",
        "dessert": "甜點",
        "deviled eggs": "魔鬼蛋",
        "dill": "蒔蘿",
        "dolichos bean": "扁豆",
        "dollop": "一團",
        "dough": "麵團",
        "doughnut": "甜甜圈",
        "dragonfruit": "火龍果",
        "dried apricot": "杏乾",
        "dried fruit": "乾果",
        "drumstick": "雞腿",
        "duck": "鴨肉",
        "dulse": "紅藻",
        "dumpling": "水餃",
        "durian": "榴槤",
        "eclair": "閃電泡芙",
        "edam cheese": "伊丹乳酪",
        "edamame": "毛豆",
        "eel": "鰻魚",
        "egg": "雞蛋",
        "egg white": "蛋白",
        "egg yolk": "蛋黃",
        "eggplant": "茄子",
        "elderberry": "接骨木莓",
        "elephant foot yam": "大魔芋",
        "elephant garlic": "象蒜",
        "emmental": "瑞士乳酪",
        "endive": "萵苣",
        "english muffin": "英式馬芬",
        "ensete": "假芭蕉",
        "escargots": "烤蝸牛",
        "espresso": "濃縮咖啡",
        "falafel": "中東炸豆丸",
        "farfalle": "蝴蝶麵",
        "fat hen": "藜",
        "fava beans": "蠶豆",
        "feast": "盛宴",
        "feijoa": "番石榴",
        "fennel": "茴香",
        "fettuccine": "寬麵",
        "fiddlehead": "蕨菜",
        "fig": "無花果",
        "filet mignon": "菲力牛排",
        "fillet": "魚片",
        "fillet of sole": "鰈魚片",
        "fish": "魚",
        "fish and chips": "炸魚薯條",
        "fish fillet": "魚片",
        "fish fingers": "魚條",
        "fish steak": "魚排",
        "flan": "法式烤布丁",
        "flatbread": "薄餅",
        "flatfish": "比目魚",
        "flax": "亞麻籽",
        "florence fennel": "球莖茴香",
        "flour": "麵粉",
        "fluted pumpkin": "非洲南瓜",
        "focaccia": "佛卡夏麵包",
        "fodder": "飼料",
        "foie gras": "鵝肝",
        "fondue": "起司火鍋",
        "fowl": "家禽",
        "frankfurters": "法蘭克福香腸",
        "french beans": "四季豆",
        "french bread": "法國麵包",
        "french dressing": "法式沙拉醬",
        "french fries": "薯條",
        "french onion soup": "法式洋蔥湯",
        "french toast": "法式吐司",
        "fried calamari": "炸魷魚圈",
        "fried egg": "荷包蛋",
        "fried rice": "炒飯",
        "frittata": "義式烘蛋",
        "fritter": "油炸餅",
        "frozen peas": "冷凍豌豆",
        "frozen pizza": "冷凍披薩",
        "frozen yogurt": "優格冰淇淋",
        "fruit salad": "水果沙拉",
        "fruit tea": "水果茶",
        "fruitcake": "水果蛋糕",
        "fudge": "軟糖",
        "fusilli": "螺旋麵",
        "galangal": "南薑",
        "galette": "法式薄餅",
        "garam masala": "印度香料粉",
        "garbanzo": "鷹嘴豆",
        "garlic": "大蒜",
        "garlic bread": "蒜味麵包",
        "garlic chives": "韭菜",
        "garlic sauce": "蒜蓉醬",
        "gastronomy": "美食學",
        "gazpacho": "西班牙冷湯",
        "gelatin": "明膠",
        "gem": "寶石糖",
        "gherkin": "小黃瓜",
        "gin": "琴酒",
        "ginger": "薑",
        "ginger ale": "薑汁汽水",
        "gingerbread": "薑餅",
        "ginseng": "人參",
        "gnocchi": "馬鈴薯麵疙瘩",
        "goats cheese": "山羊乳酪",
        "goji berry": "枸杞",
        "good king henry": "野菠菜",
        "goody": "糖果",
        "goose": "鵝肉",
        "gooseberry": "醋栗",
        "gorgonzola": "藍紋乳酪",
        "gouda": "高達起司",
        "gouda cheese": "高達起司",
        "goulash": "匈牙利燉肉",
        "gourd": "葫蘆",
        "grain": "穀物",
        "granola": "穀片",
        "granola bar": "穀物棒",
        "grape": "葡萄",
        "grape jelly": "葡萄果凍",
        "grapefruit": "葡萄柚",
        "grass": "草",
        "gravy": "肉汁",
        "greater plantain": "車前草",
        "greek salad": "希臘沙拉",
        "green onion": "青蔥",
        "green pepper": "青椒",
        "green tea": "綠茶",
        "grilled cheese sandwich": "起司烤三明治",
        "grilled salmon": "烤鮭魚",
        "grissini": "義式麵包條",
        "groats": "碎麥粒",
        "ground beef": "絞肉",
        "grub": "食物",
        "guacamole": "酪梨醬",
        "guar": "瓜爾豆",
        "guava": "芭樂",
        "gyoza": "煎餃",
        "gyro": "希臘捲餅",
        "habanero pepper": "哈瓦那辣椒",
        "haddock": "黑線鱈",
        "halibut": "大比目魚",
        "ham": "火腿",
        "hamburg parsley": "歐防風",
        "hamburger": "漢堡",
        "hamburger bun": "漢堡麵包",
        "hash": "馬鈴薯餞肉",
        "hay": "乾草",
        "hazelnut": "榛果",
        "herb": "香草",
        "herbal tea": "花草茶",
        "herring": "鯡魚",
        "hijiki": "羊栖菜",
        "honey": "蜂蜜",
        "honeydew melon": "哈密瓜",
        "horse gram": "豇豆",
        "horse radish": "山葵",
        "hot chocolate": "熱巧克力",
        "hot dog": "熱狗",
        "hot dog bun": "熱狗麵包",
        "hot pepper": "辣椒",
        "hot sauce": "辣醬",
        "huckleberry": "黑果越橘",
        "huevos rancheros": "墨西哥牧場蛋",
        "hummus": "鷹嘴豆泥",
        "ice": "冰",
        "ice cream": "冰淇淋",
        "iceberg lettuce": "美生菜",
        "iced tea": "冰茶",
        "indian pea": "印度豌豆",
        "indian tea": "印度茶",
        "italian dressing": "義大利沙拉醬",
        "ivy gourd": "印度絲瓜",
        "jabouticaba": "巴西葡萄",
        "jackfruit": "波羅蜜",
        "jalapeno": "墨西哥辣椒",
        "jam": "果醬",
        "jambul": "蒲桃",
        "jelly": "果凍",
        "jelly beans": "糖豆",
        "jerusalem artichoke": "菊芋",
        "jicama": "豆薯",
        "jordan almonds": "糖衣杏仁",
        "jug": "壺",
        "juice": "果汁",
        "jujube": "棗子",
        "julienne": "切絲",
        "juniper berry": "杜松子",
        "kale": "羽衣甘藍",
        "kebab": "烤肉串",
        "ketchup": "番茄醬",
        "kettle": "水壺",
        "kettle corn": "甜鹹爆米花",
        "kidney bean": "紅腰豆",
        "kingfish": "鰹魚",
        "kipper": "煙燻鯡魚",
        "kiwi fruit": "奇異果",
        "knish": "猶太餡餅",
        "kohlrabi": "大頭菜",
        "komatsuna": "小松菜",
        "kombu": "昆布",
        "kumquat": "金橘",
        "ladle": "湯勺",
        "lager": "拉格啤酒",
        "lagos bologi": "非洲葉菜",
        "lamb": "羊肉",
        "lamb chops": "羊排",
        "lamb's lettuce": "歐洲羊草",
        "lamb's quarters": "藜",
        "land cress": "陸生水芹",
        "lard": "豬油",
        "lasagna": "千層麵",
        "lasagne": "千層麵",
        "lavender": "薰衣草",
        "laver": "紫菜",
        "leek": "韭黃",
        "legume": "豆類",
        "lemon": "檸檬",
        "lemon peel": "檸檬皮",
        "lemonade": "檸檬汁",
        "lemongrass": "檸檬草",
        "lentil": "扁豆",
        "lettuce": "萵苣",
        "licorice": "甘草",
        "lima bean": "利馬豆",
        "lime": "青檸",
        "lime cordial": "青檸糖漿",
        "linguine": "扁麵",
        "link sausages": "香腸",
        "liqueur": "利口酒",
        "liquor": "烈酒",
        "liver pate": "肝醬",
        "lobster": "龍蝦",
        "lobster bisque": "龍蝦濃湯",
        "loin": "里肌肉",
        "lollipop": "棒棒糖",
        "loquat": "枇杷",
        "lotus root": "蓮藕",
        "lox": "煙燻鮭魚",
        "luffa": "絲瓜",
        "lunchmeat": "冷切肉",
        "lychee": "荔枝",
        "m&m": "M&M巧克力",
        "macadamia nut": "夏威夷豆",
        "macaron": "馬卡龍",
        "macaroni": "通心粉",
        "macaroon": "椰子球",
        "mackerel": "鯖魚",
        "maize": "玉米",
        "malabar spinach": "落葵",
        "malt": "麥芽",
        "mandarin orange": "橘子",
        "mango": "芒果",
        "maple syrup": "楓糖漿",
        "margarine": "人造奶油",
        "marinated cucumber": "醃黃瓜",
        "marinated herring": "醃鯡魚",
        "marionberry": "黑莓",
        "marjoram": "馬鬱蘭",
        "marmalade": "橘子醬",
        "marron": "栗子",
        "marrow": "骨髓",
        "marshmallow": "棉花糖",
        "martini": "馬丁尼",
        "marzipan": "杏仁糖膏",
        "mashed potatoes": "馬鈴薯泥",
        "mashua": "秘魯地瓜",
        "matcha": "抹茶",
        "mate": "馬黛茶",
        "mayonnaise": "美乃滋",
        "mead": "蜂蜜酒",
        "meat": "肉",
        "meat pie": "肉派",
        "meat sauce": "肉醬",
        "meatball": "肉丸",
        "meatloaf": "肉捲",
        "melokhia": "黃秋葵",
        "melon": "瓜",
        "meringue": "蛋白霜",
        "micronutrient": "微量營養素",
        "milk": "牛奶",
        "milk chocolate": "牛奶巧克力",
        "milkshake": "奶昔",
        "millefeuille": "千層酥",
        "millet": "小米",
        "mince": "絞肉",
        "miner's lettuce": "礦工生菜",
        "mint": "薄荷",
        "miracle fruit": "神奇果",
        "miso soup": "味噌湯",
        "mizuna greens": "水菜",
        "mocha": "摩卡",
        "mochi": "麻糬",
        "molasses": "糖蜜",
        "mole sauce": "墨西哥辣醬",
        "moth bean": "飛豆",
        "mousse": "慕斯",
        "mozuku": "海葡萄",
        "mozzarella": "馬自瑞拉起司",
        "muesli": "穀片",
        "muesli bar": "穀片棒",
        "muffin": "馬芬",
        "mulberry": "桑椹",
        "mung bean": "綠豆",
        "mushroom": "蘑菇",
        "mussel": "淡菜",
        "mustard": "芥末",
        "mutton": "羊肉",
        "nachos": "墨西哥玉米脆片",
        "napa cabbage": "大白菜",
        "nectar": "蜜汁",
        "nectarine": "油桃",
        "new zealand spinach": "紐西蘭菠菜",
        "nibble": "點心",
        "nigiri": "握壽司",
        "noodle": "麵條",
        "nopal": "仙人掌",
        "nori": "海苔",
        "nougat": "牛軋糖",
        "nugget": "雞塊",
        "nut": "堅果",
        "nutmeg": "肉豆蔻",
        "oat": "燕麥",
        "oatmeal": "燕麥粥",
        "oatmeal cereal": "燕麥片",
        "oatmeal cookie": "燕麥餅乾",
        "octopus": "章魚",
        "ogonori": "紅藻",
        "oil": "油",
        "okra": "秋葵",
        "olive": "橄欖",
        "olive oil": "橄欖油",
        "omelet": "蛋捲",
        "omelette": "蛋捲",
        "onion": "洋蔥",
        "onion rings": "洋蔥圈",
        "orache": "藜",
        "orange": "柳橙",
        "orange juice": "柳橙汁",
        "orange squash": "橙汁濃縮液",
        "oregano": "牛至草",
        "oyster": "牡蠣",
        "pad thai": "泰式炒河粉",
        "paddy": "稻田",
        "paella": "西班牙海鮮飯",
        "pak choy": "小白菜",
        "pancake": "鬆餅",
        "pancetta": "義大利培根",
        "panna cotta": "奶酪",
        "papaya": "木瓜",
        "papillote": "紙包魚",
        "paprika": "甜椒粉",
        "paracress": "麻葉",
        "parfait": "芭菲",
        "parmesan": "帕瑪森起司",
        "parsley": "荷蘭芹",
        "parsnip": "防風草",
        "passionfruit": "百香果",
        "pasta": "義大利麵",
        "pasta sauce": "義大利麵醬",
        "pastrami": "燻牛肉",
        "pastry": "糕點",
        "pasture": "牧草",
        "pate": "肝醬",
        "pattypan squash": "花飾南瓜",
        "pavlova": "帕芙洛娃蛋糕",
        "pea": "豌豆",
        "peach": "桃子",
        "peanut": "花生",
        "peanut butter": "花生醬",
        "peapod": "豌豆莢",
        "pear": "梨子",
        "pearl onion": "珍珠洋蔥",
        "pecan": "胡桃",
        "penne": "管通粉",
        "pepper": "胡椒",
        "peppercorn": "胡椒粒",
        "peppermint": "薄荷",
        "pepperoni": "義大利辣香腸",
        "perch": "鱸魚",
        "persimmon": "柿子",
        "pesto": "羅勒青醬",
        "pho": "越南河粉",
        "physalis": "燈籠果",
        "pickle": "醃菜",
        "pickled cucumber": "醃黃瓜",
        "pie": "派",
        "pigeon pea": "木豆",
        "pignut": "豬堅果",
        "pike": "梭魚",
        "pilaf": "抓飯",
        "pilchard": "沙丁魚",
        "pine nut": "松子",
        "pineapple": "鳳梨",
        "pistachio": "開心果",
        "pita bread": "皮塔餅",
        "pizza": "披薩",
        "plaice": "比目魚",
        "plain flour": "中筋麵粉",
        "platter": "拼盤",
        "plum": "李子",
        "polenta": "玉米糊",
        "pomegranate": "石榴",
        "pomelo": "柚子",
        "popcorn": "爆米花",
        "popovers": "約克郡布丁",
        "poppy seed roll": "罌粟籽卷",
        "popsicle": "冰棒",
        "pork": "豬肉",
        "pork chop": "豬排",
        "pork pie": "豬肉派",
        "porridge": "粥",
        "pot roast": "燉肉",
        "potato": "馬鈴薯",
        "potato onion": "馬鈴薯洋蔥",
        "poutine": "加拿大起司薯條",
        "prairie turnip": "草原蘿蔔",
        "praline": "果仁糖",
        "prawn": "蝦",
        "pretzel": "蝴蝶圈餅",
        "prime rib": "肋眼牛排",
        "prosciutto": "帕瑪火腿",
        "prune": "梅乾",
        "prussian asparagus": "普魯士蘆筍",
        "pudding": "布丁",
        "puff": "泡芙",
        "pumpernickel": "黑麥麵包",
        "pumpkin": "南瓜",
        "pumpkin seeds": "南瓜子",
        "puree": "果泥",
        "purple mangosteen": "山竹",
        "quiche": "法式鹹派",
        "quince": "榲桲",
        "quinoa": "藜麥",
        "radicchio": "紅菊苣",
        "radish": "蘿蔔",
        "raisin": "葡萄乾",
        "raisin bread": "葡萄乾麵包",
        "raisin muffin": "葡萄乾馬芬",
        "rambutan": "紅毛丹",
        "ramen": "拉麵",
        "rapini": "芥蘭",
        "raspberry": "覆盆子",
        "ratatouille": "普羅旺斯燉菜",
        "ration": "口糧",
        "ravioli": "義大利餃",
        "red cabbage": "紫高麗菜",
        "red pepper": "紅椒",
        "red velvet cake": "紅絲絨蛋糕",
        "red wine": "紅酒",
        "redcurrant": "紅醋栗",
        "relish": "醃菜醬",
        "rhubarb": "大黃",
        "rib": "排骨",
        "rice": "米飯",
        "rice flake": "米片",
        "ricebean": "飯豆",
        "ricotta": "乳清起司",
        "risotto": "燉飯",
        "roast beef": "烤牛肉",
        "roe": "魚卵",
        "romaine": "蘿蔓生菜",
        "roquefort": "羅克福乳酪",
        "rose": "玫瑰",
        "rosemary": "迷迭香",
        "roulade": "瑞士捲",
        "rum": "蘭姆酒",
        "runner bean": "菜豆",
        "russian dressing": "俄式沙拉醬",
        "rutabaga": "蕪菁",
        "rye": "黑麥",
        "rye bread": "黑麥麵包",
        "saffron": "藏紅花",
        "sage": "鼠尾草",
        "sake": "清酒",
        "salad": "沙拉",
        "salad dressing": "沙拉醬",
        "salal": "沙拉爾漿果",
        "salami": "義大利臘腸",
        "salmon": "鮭魚",
        "salmon steak": "鮭魚排",
        "salmonberry": "鮭莓",
        "salsa": "莎莎醬",
        "salsify": "婆羅門參",
        "salt": "鹽",
        "salted fish": "鹹魚",
        "samosa": "印度咖哩角",
        "samphire": "海蓬菜",
        "sandwich": "三明治",
        "sardine": "沙丁魚",
        "sashimi": "生魚片",
        "satsuma": "蜜柑",
        "sauce": "醬料",
        "sauerkraut": "德式酸菜",
        "sausage": "香腸",
        "sausage roll": "香腸麵包捲",
        "saute": "快炒",
        "scallion": "蔥",
        "scallop": "干貝",
        "scampi": "大蝦",
        "scone": "司康",
        "scorzonera": "黑牡丹",
        "scrambled": "炒蛋",
        "sea bass": "海鱸魚",
        "sea beet": "海甜菜",
        "sea grape": "海葡萄",
        "sea kale": "海甘藍",
        "sea lettuce": "海萵苣",
        "sea perch": "海鱸",
        "seafood": "海鮮",
        "seaweed salad": "海藻沙拉",
        "sesame roll": "芝麻捲",
        "sesame seed": "芝麻",
        "shallot": "紅蔥頭",
        "shandy": "啤酒汽水",
        "shellfish": "貝類",
        "sherbet": "雪酪",
        "shish kebab": "烤肉串",
        "shortcake": "水果奶油蛋糕",
        "shrimp": "蝦子",
        "sierra leone bologi": "獅子山共和國玻璃魚",
        "sirloin": "沙朗牛排",
        "skewer": "串燒",
        "skirret": "球根芹",
        "slaw": "生菜沙拉",
        "sliced loaf": "切片麵包",
        "smoked fish": "燻魚",
        "smoked salmon": "燻鮭魚",
        "smoked sausage": "煙燻香腸",
        "smoothie": "冰沙",
        "snap pea": "甜豆",
        "snapper": "鯛魚",
        "snow pea": "豌豆",
        "soda": "汽水",
        "soda bread": "蘇打麵包",
        "sorbet": "冰砂",
        "sorghum": "高粱",
        "sorrel": "酸模",
        "souffle": "舒芙蕾",
        "soup": "湯",
        "sour cabbage": "酸高麗菜",
        "sour cream": "酸奶油",
        "sourdough bread": "酸種麵包",
        "soy": "黃豆",
        "soy sauce": "醬油",
        "spaghetti": "義大利麵",
        "spaghetti bolognese": "肉醬義大利麵",
        "spaghetti carbonara": "培根奶油義大利麵",
        "spaghetti sauce": "義大利麵醬",
        "spam": "午餐肉",
        "spare ribs": "排骨",
        "spatula": "鍋鏟",
        "spearmint": "薄荷",
        "spices": "香料",
        "spinach": "菠菜",
        "split peas": "切開的豌豆",
        "sponge cake": "海綿蛋糕",
        "spongecake": "海綿蛋糕",
        "spork": "湯匙叉",
        "spread": "抹醬",
        "spring onion": "青蔥",
        "spring rolls": "春捲",
        "sprinkles": "糖針",
        "sprouts": "豆芽",
        "spuds": "馬鈴薯",
        "squash": "南瓜",
        "squash blossoms": "南瓜花",
        "squid": "魷魚",
        "star fruit": "楊桃",
        "steak": "牛排",
        "steak sauce": "牛排醬",
        "stir-fry": "炒菜",
        "stout": "黑啤酒",
        "straw": "吸管",
        "strawberry": "草莓",
        "string bean": "四季豆",
        "strudel": "果醬捲",
        "sturgeon": "鱘魚",
        "succotash": "玉米豆",
        "suet": "牛油",
        "sultanas": "葡萄乾",
        "summer purslane": "馬齒莧",
        "summer squash": "夏南瓜",
        "sundae": "聖代",
        "sunflower": "向日葵",
        "sunflower seeds": "葵花子",
        "supper": "晚餐",
        "sushi": "壽司",
        "swede": "蕪菁",
        "sweet": "甜食",
        "sweet cherry": "櫻桃",
        "sweet corn": "玉米",
        "sweet pepper": "甜椒",
        "sweet potato": "地瓜",
        "sweet-and-sour sauce": "糖醋醬",
        "sweetmeat": "糖果",
        "swiss chard": "瑞士甜菜",
        "swiss cheese": "瑞士乳酪",
        "syrup": "糖漿",
        "tabouli": "塔布里",
        "tacos": "墨西哥夾餅",
        "tagliatelle": "寬麵條",
        "tajine": "塔吉鍋",
        "takoyaki": "章魚燒",
        "tamale": "墨西哥玉米粽",
        "tamarillo": "樹番茄",
        "tamarind": "羅望子",
        "tangerine": "橘子",
        "tapioca": "木薯粉",
        "taro": "芋頭",
        "tarragon": "龍蒿",
        "tart": "果醬塔",
        "tartare": "韃靼",
        "tartlet": "小塔",
        "tarwi": "羽扇豆",
        "tatsoi": "塔菜",
        "tea": "茶",
        "tempura": "天婦羅",
        "tenderloin": "里肌肉",
        "tepary bean": "沙漠豆",
        "tequila": "龍舌蘭酒",
        "teriyaki": "照燒",
        "thyme": "百里香",
        "tigernut": "虎堅果",
        "tinda": "印度小南瓜",
        "tiramisu": "提拉米蘇",
        "toast": "吐司",
        "toffee": "太妃糖",
        "tofu": "豆腐",
        "tomatillo": "綠番茄",
        "tomato": "番茄",
        "tomato sauce": "番茄醬",
        "tongue": "牛舌",
        "tonic": "通寧水",
        "torte": "德式蛋糕",
        "tortellini": "義大利餃",
        "tortilla chips": "墨西哥玉米脆片",
        "tree onion": "樹蔥",
        "trout": "鱒魚",
        "truffle": "松露",
        "tuber": "塊莖",
        "tuna": "鮪魚",
        "tuna tartare": "生鮪魚糜",
        "turkey": "火雞",
        "turkey breast": "火雞胸肉",
        "turmeric": "薑黃",
        "turnip": "白蘿蔔",
        "tzatziki": "希臘優格醬",
        "ugli fruit": "醜柑",
        "ulluco": "馬鈴薯親戚",
        "unleavened": "未發酵的",
        "urad bean": "黑豆",
        "veal": "小牛肉",
        "veal cutlet": "小牛排",
        "vegetable": "蔬菜",
        "velvet bean": "絨毛豆",
        "venison": "鹿肉",
        "vermicelli": "粉條",
        "vermouth": "苦艾酒",
        "viennese": "維也納式的",
        "vinaigrette": "油醋醬",
        "vinegar": "醋",
        "vino": "葡萄酒",
        "vodka": "伏特加",
        "wafer": "薄餅",
        "waffle": "鬆餅",
        "wakame": "裙帶菜",
        "walnut": "核桃",
        "wasabi": "芥末",
        "water": "水",
        "water caltrop": "菱角",
        "water chestnut": "荸薺",
        "water spinach": "空心菜",
        "watercress": "西洋菜",
        "watermelon": "西瓜",
        "welsh onion": "大蔥",
        "wheat": "小麥",
        "wheat bread": "全麥麵包",
        "wheat flake": "麥片",
        "whey": "乳清",
        "whipped cream": "鮮奶油",
        "whisky": "威士忌",
        "white sauce": "白醬",
        "white wine": "白葡萄酒",
        "whoopie pie": "巧派",
        "whortleberry": "越橘",
        "wiener": "維也納香腸",
        "wild leek": "野蒜",
        "wine": "葡萄酒",
        "winged bean": "四角豆",
        "winter melon": "冬瓜",
        "yam": "山藥",
        "yao choy": "油菜",
        "yardlong bean": "長豇豆",
        "yarrow": "蓍草",
        "yeast": "酵母",
        "yellow summer squash": "黃色夏南瓜",
        "yogurt": "優格",
        "yolk": "蛋黃",
        "zucchini": "櫛瓜"
    ]
    
    
    static var examples : [PhotoInputedIngredient] = {
        let staticTitles : [(String, String)] = [("蘋果", "柳橙"), ("秋葵", "羅勒"), ("蛋", "大蒜" )]
        let results =  staticTitles.enumerated().compactMap() { index, titles in
            let image = UIImage.ingredientImages[index]!

            return PhotoInputedIngredient(image: image, leftTitle: titles.0, rightTitle: titles.1)
            
        }
        return results
       
    }()
}
