

import UIKit
enum Side {
    case left
    case right
}

class PhotoInputedIngredient : Equatable {
    static func == (lhs: PhotoInputedIngredient, rhs: PhotoInputedIngredient) -> Bool {
        lhs.title == rhs.title
    }
    
    var image : UIImage!
    
    var title : String?
    
    var buttonSide : Side?
    
    var leftPropablyTitle : String?
    
    var rightPropablyTitle : String?
    
    var outputedIngredient : Ingredient?
    
    init(image : UIImage) {
        self.image = image
    }
    
    init(image : UIImage, leftTitle : String?, rightTitle : String?) {
        self.image = image
        self.leftPropablyTitle = leftTitle
        self.rightPropablyTitle = rightTitle
    }
    
    func getTranslatedName(key : String?) -> String? {
        guard let key = key else {
            return nil
        }
        if let name = PhotoInputedIngredient.recognizeTranslateDict[key] {
            return name
        }
        return key
        
    }
    
    static let recognizeTranslateDict : Dictionary<String, String> = [
        "acorn squash": "橡實南瓜",
        "almond": "杏仁",
        "amaranth": "莧菜",
        "anchovy": "鯷魚",
        "antipasto": "開胃菜",
        "apple": "蘋果",
        "apple pie": "蘋果派",
        "apple sauce": "蘋果醬",
        "apricot": "杏",
        "artichoke": "朝鮮薊",
        "arugula": "芝麻菜",
        "asparagus": "蘆筍",
        "aspic": "肉凍",
        "avocado": "酪梨",
        "baby back ribs": "嬰肋排",
        "bacon": "培根",
        "bagel": "貝果",
        "baguette": "法棍",
        "baked alaska": "焗阿拉斯加",
        "baklava": "蜜餞酥",
        "bamboo shoots": "竹筍",
        "banana": "香蕉",
        "barley": "大麥",
        "basil": "羅勒",
        "bass": "鱸魚",
        "bay leaf": "月桂葉",
        "beancurd": "豆腐",
        "beans": "豆",
        "beef": "牛肉",
        "beef carpaccio": "生牛肉片",
        "beef steak": "牛排",
        "beef tartare": "牛肉他他",
        "beet": "甜菜根",
        "beet salad": "甜菜沙拉",
        "beignets": "油炸糕點",
        "bell pepper": "甜椒",
        "berry": "莓果",
        "bibimbap": "拌飯",
        "bilberry": "歐洲越橘",
        "birthday cake": "生日蛋糕",
        "biscuits": "餅乾",
        "bitter melon": "苦瓜",
        "black beans": "黑豆",
        "black currant": "黑加侖",
        "blackberry": "黑莓",
        "blood orange": "血橙",
        "blood sausage": "血腸",
        "blue cheese": "藍紋起司",
        "blueberry": "藍莓",
        "blueberry pie": "藍莓派",
        "bok choy": "青江菜",
        "bonbon": "軟糖",
        "boysenberry": "波森莓",
        "bread": "麵包",
        "bread pudding": "麵包布丁",
        "bread rolls": "麵包卷",
        "breadfruit": "麵包樹果",
        "breadstick": "麵包棒",
        "bream": "鯛魚",
        "brie": "布里起司",
        "brioche": "奶油小圓麵包",
        "brisket": "牛腩",
        "brittle": "脆糖",
        "broad beans": "蠶豆",
        "broccoli": "西蘭花",
        "broccolini": "小蘭花",
        "brown rice": "糙米",
        "brownie": "布朗尼",
        "brulee": "布蕾",
        "bruschetta": "布魯斯凱塔",
        "brussels sprout": "抱子甘藍",
        "buckwheat": "蕎麥",
        "burrito": "墨西哥捲餅",
        "butter": "奶油",
        "cabbage": "捲心菜",
        "caesar salad": "凱撒沙拉",
        "cake": "蛋糕",
        "cake pop": "蛋糕棒",
        "calamari": "炸魷魚",
        "camembert": "卡門貝爾起司",
        "canape": "小吃",
        "candy": "糖果",
        "candy apple": "糖蘋果",
        "candy bar": "糖果棒",
        "cannoli": "卡諾利",
        "cantaloupe": "哈密瓜",
        "caper": "酸豆",
        "caprese salad": "卡普雷塞沙拉",
        "caramel apple": "焦糖蘋果",
        "cardoon": "洋薊",
        "carp": "鯉魚",
        "carpaccio": "生魚片",
        "carrot": "胡蘿蔔",
        "carrot cake": "胡蘿蔔蛋糕",
        "cashew": "腰果",
        "cassava": "木薯",
        "casserole": "燉菜",
        "cauliflower": "花椰菜",
        "caviar": "魚子醬",
        "celery": "芹菜",
        "cereal": "穀物",
        "ceviche": "酸橘汁醃魚",
        "chard": "莙薘菜",
        "cheddar": "切達起司",
        "cheese": "起司",
        "cheeseburger": "起司漢堡",
        "cheesecake": "起司蛋糕",
        "cherry": "櫻桃",
        "cherry tomato": "小番茄",
        "chestnut": "栗子",
        "chicken": "雞肉",
        "chicken breast": "雞胸肉",
        "chicken curry": "雞肉咖哩",
        "chicken leg": "雞腿",
        "chicken wings": "雞翅",
        "chickpeas": "鷹嘴豆",
        "chili": "辣椒",
        "chili pepper": "辣椒",
        "chips": "薯片",
        "chives": "韭菜",
        "chocolate": "巧克力",
        "chorizo": "辣香腸",
        "chowder": "濃湯",
        "churros": "吉拿棒",
        "chutney": "酸辣醬",
        "ciabatta": "恰巴塔",
        "cinnamon roll": "肉桂捲",
        "citron": "香橙",
        "citrus": "柑橘",
        "clam": "蛤蜊",
        "clam chowder": "蛤蜊濃湯",
        "clementine": "克萊門氏小柑橘",
        "cobbler": "果餡餅",
        "cockle": "扇貝",
        "coconut": "椰子",
        "coleslaw": "涼拌捲心菜",
        "collards": "甘藍",
        "common bean": "普通豆",
        "compote": "果泥",
        "cookie": "餅乾",
        "corn": "玉米",
        "corn bread": "玉米麵包",
        "corn salad": "玉米沙拉",
        "corned beef": "鹹牛肉",
        "cornflakes": "玉米片",
        "cottage cheese": "農家起司",
        "couscous": "庫斯庫斯",
        "crab": "螃蟹",
        "crab cakes": "蟹餅",
        "cracker": "薄脆餅乾",
        "cranberry": "蔓越莓",
        "crayfish": "小龍蝦",
        "creme brulee": "焦糖布蕾",
        "crepe": "可麗餅",
        "crescent roll": "新月麵包",
        "cress": "水芹",
        "crispbread": "脆麵包",
        "croissant": "羊角麵包",
        "croque madame": "法式煎蛋吐司",
        "croquette": "炸丸子",
        "crouton": "麵包塊",
        "crunch": "脆餅",
        "cucumber": "黃瓜",
        "cupcake": "杯子蛋糕",
        "curd": "凝乳",
        "currant": "紅加侖",
        "custard": "蛋奶凍",
        "cuttlefish": "墨魚",
        "daikon": "白蘿蔔",
        "dandelion greens": "蒲公英葉",
        "danish pastry": "丹麥酥",
        "date": "棗",
        "deviled eggs": "魔鬼蛋",
        "dough": "麵團",
        "doughnut": "甜甜圈",
        "dragonfruit": "火龍果",
        "dried apricot": "乾杏",
        "dried fruit": "乾果",
        "drumstick": "雞腿",
        "duck": "鴨肉",
        "dumpling": "餃子",
        "durian": "榴槤",
        "eclair": "法式閃電泡芙",
        "edamame": "毛豆",
        "eel": "鰻魚",
        "egg": "雞蛋",
        "egg white": "蛋白",
        "egg yolk": "蛋黃",
        "eggplant": "茄子",
        "elderberry": "接骨木莓",
        "endive": "菊苣",
        "english muffin": "英式松餅",
        "escargots": "法式蝸牛",
        "falafel": "鷹嘴豆丸子",
        "farfalle": "蝴蝶麵",
        "fava beans": "蠶豆",
        "fiddlehead": "蕨菜",
        "fig": "無花果",
        "filet mignon": "菲力牛排",
        "fillet of sole": "比目魚柳",
        "fish": "魚",
        "fish and chips": "炸魚薯條",
        "flan": "法蘭布丁",
        "flatbread": "薄餅",
        "flatfish": "比目魚",
        "florence fennel": "佛羅倫斯茴香",
        "focaccia": "佛卡夏",
        "foie gras": "鵝肝",
        "fondue": "火鍋",
        "frankfurters": "法蘭克福香腸",
        "french beans": "法國豆",
        "french bread": "法式麵包",
        "french fries": "炸薯條",
        "french onion soup": "法式洋蔥湯",
        "french toast": "法式吐司",
        "fried calamari": "炸魷魚",
        "fried egg": "煎蛋",
        "fried rice": "炒飯",
        "frittata": "意大利煎蛋餅",
        "fritter": "炸果子",
        "frozen yogurt": "冷凍酸奶",
        "fruit salad": "水果沙拉",
        "fruitcake": "水果蛋糕",
        "fudge": "乳脂軟糖",
        "fusilli": "螺旋麵",
        "galette": "法式塔",
        "garlic": "大蒜",
        "garlic bread": "蒜香麵包",
        "garlic chives": "韭菜",
        "gazpacho": "西班牙冷湯",
        "gherkin": "酸黃瓜",
        "ginger": "薑",
        "gnocchi": "意式麵疙瘩",
        "goats cheese": "羊奶酪",
        "goji berry": "枸杞",
        "goose": "鵝肉",
        "gooseberry": "鵝莓",
        "gorgonzola": "戈貢佐拉起司",
        "gouda": "古達起司",
        "goulash": "匈牙利燉牛肉",
        "gourd": "葫蘆",
        "granola": "穀物麥片",
        "grape": "葡萄",
        "grapefruit": "葡萄柚",
        "greek salad": "希臘沙拉",
        "green bean": "青豆",
        "green onion": "青蔥",
        "grilled cheese sandwich": "烤起司三明治",
        "grits": "玉米粥",
        "ground beef": "絞牛肉",
        "guacamole": "牛油果醬",
        "guava": "芭樂",
        "gyoza": "餃子",
        "gyro": "旋轉烤肉",
        "habanero pepper": "哈瓦那辣椒",
        "halibut": "比目魚",
        "ham": "火腿",
        "hamburger": "漢堡",
        "hash": "肉末土豆",
        "hazelnut": "榛子",
        "herring": "鯡魚",
        "honey": "蜂蜜",
        "honeydew melon": "蜜瓜",
        "hot dog": "熱狗",
        "huckleberry": "黑果",
        "huevos rancheros": "牧場雞蛋",
        "hummus": "鷹嘴豆泥",
        "ice cream": "冰淇淋",
        "iceberg lettuce": "冰山萵苣",
        "jackfruit": "菠蘿蜜",
        "jalapeno": "墨西哥辣椒",
        "jelly beans": "軟糖豆",
        "jerusalem artichoke": "菊芋",
        "jicama": "豆薯",
        "jordan almonds": "糖杏仁",
        "jujube": "棗",
        "juniper berry": "杜松子",
        "kale": "羽衣甘藍",
        "kebab": "烤肉串",
        "kettle corn": "甜味爆米花",
        "kidney bean": "腎豆",
        "kingfish": "皇魚",
        "kipper": "燻魚",
        "kiwi fruit": "奇異果",
        "knish": "餡餅",
        "kohlrabi": "球莖甘藍",
        "kombu": "昆布",
        "kumquat": "金桔",
        "lamb": "羊肉",
        "lamb chops": "羊排",
        "lamb's lettuce": "羊角菜",
        "lasagna": "千層麵",
        "lavender": "薰衣草",
        "leek": "韭蔥",
        "lemon": "檸檬",
        "lemon peel": "檸檬皮",
        "lentil": "扁豆",
        "lettuce": "生菜",
        "lima bean": "利馬豆",
        "lime": "萊姆",
        "lobster": "龍蝦",
        "lobster bisque": "龍蝦湯",
        "loin": "腰肉",
        "lollipop": "棒棒糖",
        "lotus root": "蓮藕",
        "lox": "煙熏三文魚",
        "lychee": "荔枝",
        "macadamia nut": "夏威夷果",
        "macaron": "馬卡龍",
        "macaroni": "通心粉",
        "macaroon": "椰蓉餅",
        "mackerel": "鯖魚",
        "mandarin orange": "柑橘",
        "mango": "芒果",
        "maple syrup": "楓糖漿",
        "marjoram": "馬鬱蘭",
        "marshmallow": "棉花糖",
        "marzipan": "杏仁膏",
        "mashed potatoes": "馬鈴薯泥",
        "meat": "肉",
        "meat pie": "肉餡餅",
        "meatball": "肉丸",
        "meatloaf": "肉餅",
        "melon": "瓜",
        "meringue": "蛋白霜",
        "millet": "小米",
        "mint": "薄荷",
        "miso soup": "味噌湯",
        "mochi": "麻糬",
        "mousse": "慕斯",
        "mozzarella": "馬蘇里拉",
        "muesli": "穀物麥片",
        "muffin": "馬芬",
        "mulberry": "桑葚",
        "mung bean": "綠豆",
        "mushroom": "蘑菇",
        "mussel": "貽貝",
        "mutton": "羊肉",
        "nachos": "玉米片",
        "napa cabbage": "大白菜",
        "nectarine": "油桃",
        "nigiri": "握壽司",
        "noodle": "麵",
        "nori": "紫菜",
        "nougat": "牛軋糖",
        "nut": "堅果",
        "oat": "燕麥",
        "oatmeal": "燕麥粥",
        "octopus": "章魚",
        "okra": "秋葵",
        "olive": "橄欖",
        "omelette": "煎蛋",
        "onion": "洋蔥",
        "onion rings": "洋蔥圈",
        "orange": "橙子",
        "oyster": "牡蠣",
        "pad thai": "泰式炒河粉",
        "paella": "西班牙海鮮飯",
        "pancake": "鬆餅",
        "pancetta": "五花肉",
        "papaya": "木瓜",
        "parfait": "百匯",
        "parmesan": "帕爾瑪起司",
        "parsley": "香菜",
        "parsnip": "歐防風",
        "passion fruit": "百香果",
        "pasta": "義大利麵",
        "pasty": "餡餅",
        "pate": "肉餡餅",
        "pea": "豌豆",
        "peach": "桃子",
        "peanut": "花生",
        "peanut butter": "花生醬",
        "pearl onion": "珍珠洋蔥",
        "pear": "梨",
        "pecan": "碧根果",
        "pecan pie": "碧根果派",
        "pecorino": "佩科里諾起司",
        "pepper": "胡椒",
        "pepperoni": "辣味香腸",
        "persimmon": "柿子",
        "pheasant": "雉雞",
        "pickle": "酸黃瓜",
        "pie": "派",
        "pilaf": "肉飯",
        "pine nut": "松子",
        "pineapple": "鳳梨",
        "pita": "皮塔餅",
        "pizza": "披薩",
        "plantain": "大蕉",
        "plum": "李子",
        "plum tomato": "李子番茄",
        "pomegranate": "石榴",
        "pomelo": "柚子",
        "popcorn": "爆米花",
        "popovers": "爆餡麵包",
        "popsicle": "冰棒",
        "porcini": "牛肝菌",
        "pork": "豬肉",
        "pork belly": "五花肉",
        "pork chop": "豬排",
        "pork loin": "豬腰肉",
        "pork ribs": "豬肋排",
        "pork tenderloin": "豬里脊",
        "potato": "馬鈴薯",
        "potato chips": "馬鈴薯片",
        "potato salad": "馬鈴薯沙拉",
        "potpie": "焗派",
        "prawn": "大蝦",
        "pretzel": "蝴蝶餅",
        "prosciutto": "意式火腿",
        "prune": "西梅",
        "pudding": "布丁",
        "pumpernickel": "黑麥麵包",
        "pumpkin": "南瓜",
        "quail": "鵪鶉",
        "quiche": "乳蛋餅",
        "quinoa": "藜麥",
        "radicchio": "紫萵苣",
        "radish": "蘿蔔",
        "raisin": "葡萄乾",
        "raspberry": "覆盆子",
        "ravioli": "意大利餛飩",
        "red cabbage": "紅卷心菜",
        "red snapper": "紅鯛",
        "rhubarb": "大黃",
        "rib eye steak": "肋眼牛排",
        "ricotta": "里科塔起司",
        "risotto": "燉飯",
        "roast beef": "烤牛肉",
        "roast chicken": "烤雞",
        "romaine": "羅馬生菜",
        "rosemary": "迷迭香",
        "roti": "印度烤餅",
        "rump steak": "臀部牛排",
        "rye bread": "黑麥麵包",
        "saffron": "藏紅花",
        "sage": "鼠尾草",
        "sake": "清酒",
        "salad": "沙拉",
        "salami": "意大利香腸",
        "salmon": "三文魚",
        "salsa": "莎莎醬",
        "salt": "鹽",
        "salted fish": "鹽漬魚",
        "samosa": "薩莫薩",
        "sandwich": "三明治",
        "sardine": "沙丁魚",
        "sashimi": "生魚片",
        "sauerkraut": "德國酸菜",
        "sausage": "香腸",
        "scallion": "蔥",
        "scallop": "扇貝",
        "sea bass": "海鱸魚",
        "seaweed": "海藻",
        "semolina": "粗麥粉",
        "sesame": "芝麻",
        "shallot": "紅蔥頭",
        "sherbet": "雪酪",
        "shrimp": "蝦",
        "skewer": "烤串",
        "slaw": "捲心菜沙拉",
        "snap pea": "豌豆",
        "snapper": "紅鯛",
        "snow pea": "雪豆",
        "soda bread": "蘇打麵包",
        "sorbet": "雪葩",
        "sour cream": "酸奶油",
        "soy": "大豆",
        "soy sauce": "醬油",
        "spaghetti": "意大利麵",
        "spare ribs": "排骨",
        "spinach": "菠菜",
        "sponge cake": "海綿蛋糕",
        "sprout": "芽",
        "squid": "魷魚",
        "steak": "牛排",
        "stew": "燉菜",
        "stilton": "斯提爾頓起司",
        "strawberry": "草莓",
        "strudel": "果餡卷",
        "stuffing": "填料",
        "succotash": "玉米豆蔻雜燴",
        "sugar": "糖",
        "sugar cane": "甘蔗",
        "sugar snap pea": "糖莢豆",
        "sultana": "葡萄乾",
        "summer squash": "夏南瓜",
        "sundae": "聖代",
        "sushi": "壽司",
        "sweet corn": "甜玉米",
        "sweet potato": "甘薯",
        "swiss chard": "瑞士甜菜",
        "swordfish": "劍魚",
        "tabbouleh": "阿拉伯沙拉",
        "taco": "塔可",
        "tahini": "芝麻醬",
        "taleggio": "塔雷吉奧起司",
        "tamale": "墨西哥玉米卷",
        "tangelo": "橙柑",
        "tangerine": "橘子",
        "tapioca": "木薯粉",
        "tarragon": "龍蒿",
        "tart": "塔",
        "tartar sauce": "塔塔醬",
        "tartare": "他他",
        "tea": "茶",
        "tempeh": "天貝",
        "tempura": "天婦羅",
        "teriyaki": "照燒",
        "thyme": "百里香",
        "tilapia": "羅非魚",
        "tofu": "豆腐",
        "tomatillo": "番茄屬",
        "tomato": "番茄",
        "torte": "蛋糕",
        "tortellini": "意大利小餛飩",
        "tortilla": "玉米餅",
        "trifle": "果凍布丁",
        "trout": "鱒魚",
        "truffle": "松露",
        "tuna": "金槍魚",
        "turkey": "火雞",
        "turnip": "蕪菁",
        "upside-down cake": "翻轉蛋糕",
        "veal": "小牛肉",
        "vegetable": "蔬菜",
        "venison": "鹿肉",
        "vermicelli": "粉絲",
        "vinegar": "醋",
        "waffle": "鬆餅",
        "wakame": "若芽",
        "walnut": "核桃",
        "wasabi": "芥末",
        "water": "水",
        "water chestnut": "荸薺",
        "watercress": "西洋菜",
        "watermelon": "西瓜",
        "wheat": "小麥",
        "wheat bran": "小麥糠",
        "wheat germ": "麥胚",
        "whiting": "鱈魚",
        "wild rice": "野米",
        "wine": "葡萄酒",
        "winter melon": "冬瓜",
        "wolfberry": "枸杞",
        "yam": "山藥",
        "yeast": "酵母",
        "yellowfin tuna": "黃鰭金槍魚",
        "yogurt": "酸奶",
        "zucchini": "西葫蘆"
    ]
    
    
    static var examples : [PhotoInputedIngredient] = {
        let staticTitles : [(String, String)] = [("牛番茄", "蓮霧"), ("雞蛋", "鱈魚丸"), ("空心菜", "水蓮" )]
        let results =  staticTitles.enumerated().compactMap() { index, titles in
            let image = UIImage.ingredientImages[index]!

            return PhotoInputedIngredient(image: image, leftTitle: titles.0, rightTitle: titles.1)
            
        }
        return results
       
    }()
}
